### ISSUE TITLE
Error after reload site (when it was open since a moment)

### ISSUE THREAD

**Issue by alcaidio** [TanStack/tanstack.com#219]
<img width="724" alt="Capture d’écran 2024-04-30 à 16 28 07" src="https://github.com/TanStack/tanstack.com/assets/17033036/6a907622-5691-401c-9b65-fe24b2726126">
```

client-BTQNNC8X.js:38 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at fo (client-BTQNNC8X.js:38:5251)
    at ph (client-BTQNNC8X.js:40:15336)
    at cf (client-BTQNNC8X.js:40:39943)
    at uf (client-BTQNNC8X.js:40:39696)
    at kh (client-BTQNNC8X.js:40:39607)
    at sf (client-BTQNNC8X.js:40:34618)
    at S (client-BTQNNC8X.js:25:1563)
    at MessagePort.M (client-BTQNNC8X.js:25:1930)
client-BTQNNC8X.js:40 Uncaught Error: Minified React error #422; visit https://reactjs.org/docs/error-decoder.html?invariant=422 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at dh (client-BTQNNC8X.js:40:8427)
    at qd (client-BTQNNC8X.js:40:7368)
    at ff (client-BTQNNC8X.js:40:45629)
    at uf (client-BTQNNC8X.js:40:39635)
    at kh (client-BTQNNC8X.js:40:39607)
    at sf (client-BTQNNC8X.js:40:34618)
    at S (client-BTQNNC8X.js:25:1563)
    at MessagePort.M (client-BTQNNC8X.js:25:1930)
client-BTQNNC8X.js:542 DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25276)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
client-BTQNNC8X.js:38 Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25276)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
    at tl (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25399)
client-BTQNNC8X.js:542 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26002)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26457)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26457)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26457)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26650)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
client-BTQNNC8X.js:38 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26002)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26457)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26457)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26457)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
    at nf (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:26650)
    at It (https://tanstack.com/_build/assets/client-BTQNNC8X.js:40:25708)
45982155.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at 45982155.js:1:289
    at 45982155.js:1:319

```

**Comment by gardevgranade** [comment]
Same here https://github.com/TanStack/tanstack.com/assets/23475952/dd703436-30bb-4b2f-8cee-09e3598e00a8

By turning off browser plugins such as Coupert it is working

**Comment by SeanCassiere** [comment]
This should be resolved now.
